//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversionClient
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MassRequest", Namespace = "http://schemas.datacontract.org/2004/07/WebServer.Models.Dto")]
    public partial class MassRequest : object
    {

        private ConversionClient.MassUnit FromField;

        private ConversionClient.MassUnit ToField;

        private double ValueField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConversionClient.MassUnit From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConversionClient.MassUnit To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MassUnit", Namespace = "http://schemas.datacontract.org/2004/07/WebServer.Enums")]
    public enum MassUnit : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        mg = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        g = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        kg = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        lb = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        oz = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        t = 5,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ConversionResponse", Namespace = "http://schemas.datacontract.org/2004/07/WebServer.Models.Dto")]
    public partial class ConversionResponse : object
    {

        private string MessageField;

        private double ResultField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LengthRequest", Namespace = "http://schemas.datacontract.org/2004/07/WebServer.Models.Dto")]
    public partial class LengthRequest : object
    {

        private ConversionClient.LengthUnit FromField;

        private ConversionClient.LengthUnit ToField;

        private double ValueField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConversionClient.LengthUnit From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConversionClient.LengthUnit To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LengthUnit", Namespace = "http://schemas.datacontract.org/2004/07/WebServer.Enums")]
    public enum LengthUnit : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        mm = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        cm = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        m = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        km = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ft = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        @in = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        yd = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        mi = 7,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TemperatureRequest", Namespace = "http://schemas.datacontract.org/2004/07/WebServer.Models.Dto")]
    public partial class TemperatureRequest : object
    {

        private ConversionClient.TemperatureUnit FromField;

        private ConversionClient.TemperatureUnit ToField;

        private double ValueField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConversionClient.TemperatureUnit From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConversionClient.TemperatureUnit To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TemperatureUnit", Namespace = "http://schemas.datacontract.org/2004/07/WebServer.Enums")]
    public enum TemperatureUnit : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        C = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        F = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        K = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ra = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Re = 4,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ConversionService.IConversionService")]
    public interface IConversionService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IConversionService/ConvertMass", ReplyAction = "http://tempuri.org/IConversionService/ConvertMassResponse")]
        System.Threading.Tasks.Task<ConversionClient.ConversionResponse> ConvertMassAsync(ConversionClient.MassRequest dto);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IConversionService/ConvertLength", ReplyAction = "http://tempuri.org/IConversionService/ConvertLengthResponse")]
        System.Threading.Tasks.Task<ConversionClient.ConversionResponse> ConvertLengthAsync(ConversionClient.LengthRequest dto);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IConversionService/ConvertTemperature", ReplyAction = "http://tempuri.org/IConversionService/ConvertTemperatureResponse")]
        System.Threading.Tasks.Task<ConversionClient.ConversionResponse> ConvertTemperatureAsync(ConversionClient.TemperatureRequest dto);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IConversionServiceChannel : ConversionClient.IConversionService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ConversionServiceClient : System.ServiceModel.ClientBase<ConversionClient.IConversionService>, ConversionClient.IConversionService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ConversionServiceClient() :
                base(ConversionServiceClient.GetDefaultBinding(), ConversionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConversionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ConversionServiceClient(EndpointConfiguration endpointConfiguration) :
                base(ConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), ConversionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ConversionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(ConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ConversionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(ConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<ConversionClient.ConversionResponse> ConvertMassAsync(ConversionClient.MassRequest dto)
        {
            return base.Channel.ConvertMassAsync(dto);
        }

        public System.Threading.Tasks.Task<ConversionClient.ConversionResponse> ConvertLengthAsync(ConversionClient.LengthRequest dto)
        {
            return base.Channel.ConvertLengthAsync(dto);
        }

        public System.Threading.Tasks.Task<ConversionClient.ConversionResponse> ConvertTemperatureAsync(ConversionClient.TemperatureRequest dto)
        {
            return base.Channel.ConvertTemperatureAsync(dto);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversionService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5119/UnitConversionService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConversionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConversionService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConversionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConversionService);
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_IConversionService,
        }
    }
}
