//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConversionClient
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MassRequest", Namespace="http://schemas.datacontract.org/2004/07/WS_CONVUNI_SOAP_DOTNET_GR01.Models.Dto")]
    public partial class MassRequest : object
    {
        
        private UnitConversionClient.MassUnit FromField;
        
        private UnitConversionClient.MassUnit ToField;
        
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitConversionClient.MassUnit From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitConversionClient.MassUnit To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MassUnit", Namespace="http://schemas.datacontract.org/2004/07/WS_CONVUNI_SOAP_DOTNET_GR01.Enums")]
    public enum MassUnit : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        mg = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        g = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        kg = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        lb = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        oz = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        t = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitConversionResponse", Namespace="http://schemas.datacontract.org/2004/07/WS_CONVUNI_SOAP_DOTNET_GR01.Models.Dto")]
    public partial class UnitConversionResponse : object
    {
        
        private string MessageField;
        
        private double ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LengthRequest", Namespace="http://schemas.datacontract.org/2004/07/WS_CONVUNI_SOAP_DOTNET_GR01.Models.Dto")]
    public partial class LengthRequest : object
    {
        
        private UnitConversionClient.LengthUnit FromField;
        
        private UnitConversionClient.LengthUnit ToField;
        
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitConversionClient.LengthUnit From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitConversionClient.LengthUnit To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LengthUnit", Namespace="http://schemas.datacontract.org/2004/07/WS_CONVUNI_SOAP_DOTNET_GR01.Enums")]
    public enum LengthUnit : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        mm = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cm = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        m = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        km = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ft = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @in = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        yd = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        mi = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemperatureRequest", Namespace="http://schemas.datacontract.org/2004/07/WS_CONVUNI_SOAP_DOTNET_GR01.Models.Dto")]
    public partial class TemperatureRequest : object
    {
        
        private UnitConversionClient.TemperatureUnit FromField;
        
        private UnitConversionClient.TemperatureUnit ToField;
        
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitConversionClient.TemperatureUnit From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitConversionClient.TemperatureUnit To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemperatureUnit", Namespace="http://schemas.datacontract.org/2004/07/WS_CONVUNI_SOAP_DOTNET_GR01.Enums")]
    public enum TemperatureUnit : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        C = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        K = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ra = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Re = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UnitConversionClient.IUnitConversionService")]
    public interface IUnitConversionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnitConversionService/ConvertMass", ReplyAction="http://tempuri.org/IUnitConversionService/ConvertMassResponse")]
        System.Threading.Tasks.Task<UnitConversionClient.UnitConversionResponse> ConvertMassAsync(UnitConversionClient.MassRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnitConversionService/ConvertLength", ReplyAction="http://tempuri.org/IUnitConversionService/ConvertLengthResponse")]
        System.Threading.Tasks.Task<UnitConversionClient.UnitConversionResponse> ConvertLengthAsync(UnitConversionClient.LengthRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUnitConversionService/ConvertTemperature", ReplyAction="http://tempuri.org/IUnitConversionService/ConvertTemperatureResponse")]
        System.Threading.Tasks.Task<UnitConversionClient.UnitConversionResponse> ConvertTemperatureAsync(UnitConversionClient.TemperatureRequest dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IUnitConversionServiceChannel : UnitConversionClient.IUnitConversionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class UnitConversionServiceClient : System.ServiceModel.ClientBase<UnitConversionClient.IUnitConversionService>, UnitConversionClient.IUnitConversionService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UnitConversionServiceClient() : 
                base(UnitConversionServiceClient.GetDefaultBinding(), UnitConversionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUnitConversionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UnitConversionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UnitConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), UnitConversionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UnitConversionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UnitConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UnitConversionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UnitConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UnitConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<UnitConversionClient.UnitConversionResponse> ConvertMassAsync(UnitConversionClient.MassRequest dto)
        {
            return base.Channel.ConvertMassAsync(dto);
        }
        
        public System.Threading.Tasks.Task<UnitConversionClient.UnitConversionResponse> ConvertLengthAsync(UnitConversionClient.LengthRequest dto)
        {
            return base.Channel.ConvertLengthAsync(dto);
        }
        
        public System.Threading.Tasks.Task<UnitConversionClient.UnitConversionResponse> ConvertTemperatureAsync(UnitConversionClient.TemperatureRequest dto)
        {
            return base.Channel.ConvertTemperatureAsync(dto);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUnitConversionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUnitConversionService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5119/UnitConversion");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UnitConversionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUnitConversionService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UnitConversionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUnitConversionService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUnitConversionService,
        }
    }
}
